/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.util.Arrays;
import java.util.ArrayList;
import Interface.*;
import practicaventanas.Municipalidad;

/**
 *
 * @author AdminFull
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    private Municipalidad muni;

    /**
     * Creates new form FormPrincipal
     */    
    public FrmPrincipal() {
        this.muni = Municipalidad.initMunicipalidad();
        initComponents();
        lst_10UltimasMultas.setListData(muni.ultimos10());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_frmPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_10UltimasMultas = new javax.swing.JList();
        menuBar_principal = new javax.swing.JMenuBar();
        menu_infracciones = new javax.swing.JMenu();
        btn_altaInfraciones = new javax.swing.JMenuItem();
        btn_eliminarMulta = new javax.swing.JMenuItem();
        menu_reportes = new javax.swing.JMenu();
        btn_listadoMultas = new javax.swing.JMenuItem();
        btn_reporteMultas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Multas");

        jScrollPane1.setViewportView(lst_10UltimasMultas);

        javax.swing.GroupLayout panel_frmPrincipalLayout = new javax.swing.GroupLayout(panel_frmPrincipal);
        panel_frmPrincipal.setLayout(panel_frmPrincipalLayout);
        panel_frmPrincipalLayout.setHorizontalGroup(
            panel_frmPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_frmPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_frmPrincipalLayout.setVerticalGroup(
            panel_frmPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_frmPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );

        menu_infracciones.setText("Alta infracción");

        btn_altaInfraciones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        btn_altaInfraciones.setText("Alta Infraccion");
        btn_altaInfraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_altaInfracionesActionPerformed(evt);
            }
        });
        menu_infracciones.add(btn_altaInfraciones);

        btn_eliminarMulta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        btn_eliminarMulta.setText("Eliminar Multa");
        menu_infracciones.add(btn_eliminarMulta);

        menuBar_principal.add(menu_infracciones);

        menu_reportes.setText("Listado & Reportes");

        btn_listadoMultas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        btn_listadoMultas.setText("Listado de Multas");
        btn_listadoMultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listadoMultasActionPerformed(evt);
            }
        });
        menu_reportes.add(btn_listadoMultas);

        btn_reporteMultas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        btn_reporteMultas.setText("Reporte Gral");
        menu_reportes.add(btn_reporteMultas);

        menuBar_principal.add(menu_reportes);

        setJMenuBar(menuBar_principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_frmPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_frmPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_altaInfracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_altaInfracionesActionPerformed
        FrmAltaMulta frm = new FrmAltaMulta(this, true, this.muni);
        frm.setLocationRelativeTo(null);
        frm.setVisible(true);
    }//GEN-LAST:event_btn_altaInfracionesActionPerformed

    private void btn_listadoMultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listadoMultasActionPerformed
        FrmListadoMultas listado = new FrmListadoMultas(this, true, this.muni);
        listado.setLocationRelativeTo(null);
        listado.setVisible(true);
    }//GEN-LAST:event_btn_listadoMultasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               FrmPrincipal form = new FrmPrincipal();
               form.setLocationRelativeTo(null);
               form.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btn_altaInfraciones;
    private javax.swing.JMenuItem btn_eliminarMulta;
    private javax.swing.JMenuItem btn_listadoMultas;
    private javax.swing.JMenuItem btn_reporteMultas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lst_10UltimasMultas;
    private javax.swing.JMenuBar menuBar_principal;
    private javax.swing.JMenu menu_infracciones;
    private javax.swing.JMenu menu_reportes;
    private javax.swing.JPanel panel_frmPrincipal;
    // End of variables declaration//GEN-END:variables
}
